### ISSUE TITLE
Include Bonus Power into the calculation with variable "base power"

### ISSUE THREAD

**Issue by corny2710** [CableKungZ/RollercoinBestPower#1]
Could you make a separate code that includes a variable for the base power and for the existing bonus power.

So the calculation would work like this

Minerpower * (variable existing bonus power) + (miner bonus power * base power) / 1000  / price

**Comment by CableKungZ** [comment]
Okay I added new script to calculate the addition power from the bonus and current power

The formula to calculate an addition power is : (bonus/100)*(CurrentPower+Power) 
The formula to find the ratio is : ((power+addpower)/1000) / price

The code name is RC_Normal_withPower_Cal.js

**Comment by corny2710** [comment]
sorry - the bonus power percentage is missing as a second variable which should be added to the power of the miner

**Comment by CableKungZ** [comment]
> sorry - the bonus power percentage is missing as a second variable which should be added to the power of the miner

I don't understand why there is an additional bonus power variable. Since the power bonus cannot be added to the miner. that has been obtained

**Comment by corny2710** [comment]
I mean I habe 526,41% Bonus power already - if I buy a miner (let's say "Golden Fleece) with 500.000 GHs and 3% Bonus power it would give me additional 526,41% on top - if I buy AncLA with 724.000 GHs and 2% Bonus power - there is no comparision for me if the existing bonus power might give me a better Ratio because of the higher mining power or if it might be better to buy a lower-powered miner with higher bonus power

**Comment by CableKungZ** [comment]
> I mean I habe 526,41% Bonus power already - if I buy a miner (let's say "Golden Fleece) with 500.000 GHs and 3% Bonus power it would give me additional 526,41% on top - if I buy AncLA with 724.000 GHs and 2% Bonus power - there is no comparision for me if the existing bonus power might give me a better Ratio because of the higher mining power or if it might be better to buy a lower-powered miner with higher bonus power

oh ok i got it

**Comment by CableKungZ** [comment]
> I mean I habe 526,41% Bonus power already - if I buy a miner (let's say "Golden Fleece) with 500.000 GHs and 3% Bonus power it would give me additional 526,41% on top - if I buy AncLA with 724.000 GHs and 2% Bonus power - there is no comparision for me if the existing bonus power might give me a better Ratio because of the higher mining power or if it might be better to buy a lower-powered miner with higher bonus power

I just uploaded it on Github. Try using it.

**Comment by corny2710** [comment]
One more calculation is needed for the overall power that you will get if you need to choose between both miners.

overall power should include the additional existing bonus power for base power of the miner - which means 724.000 GHs * 526,41% + 724.000 GHs + 2% * existing base power (193 PHs)
and for this value we need the ratio/RLT

**Comment by CableKungZ** [comment]
I guess it already on code RC_Normal_withPower_Cal.js line 27-30 
        let addpower = (power*((bonus + CurrentBonus) / 100))+(CurrentPower*bonus); // minerpower*(minerbonus+currentbonus)+(currentpower*minerbonus)
        let totalpower = power+addpower;
        let ratio = (totalpower/1000) / price;

**Comment by corny2710** [comment]
<html>
<body>

(Index) | Name | Price | Power | Bonus | Addition[GH/S] | Ratio | TotalPower [GH/S] | Total Bonus %
-- | -- | -- | -- | -- | -- | -- | -- | --

0 | 'Candysweet' | 30.6915 | 250000 | 4 | '774517000.000' | '25243.70' | '774767000.00' | '530.000'
1 | '黃帝 (Yellow Emperor)' | 30.9 | 200000 | 3 | '580952000.000' | '18807.51' | '581152000.00' | '529.000'
2 | 'The Icarus' | 34.860003 | 225000 | 3 | '581084250.000' | '16675.54' | '581309250.00' | '529.000'
3 | 'Golden Fleece' | 36.2775 | 500000 | 3 | '582539000.000' | '16071.64' | '583039000.00' | '529.000'
4 | 'Treasure Guardian' | 36.70779 | 558000 | 3 | '582845820.000' | '15893.19' | '583403820.00' | '529.000'
5 | 'Perfection' | 36.7395 | 400000 | 3 | '582010000.000' | '15852.42' | '582410000.00' | '529.000'
6 | 'Paradox' | 38.64 | 350000 | 3 | '581745500.000' | '15064.58' | '582095500.00' | '529.000'
7 | 'Diving Mask' | 38.85 | 550000 | 3 | '582803500.000' | '15015.53' | '583353500.00' | '529.000'
8 | 'Fluffy-Miner' | 39.795 | 550000 | 3 | '582803500.000' | '14658.96' | '583353500.00' | '529.000'
9 | "Pandora's Box" | 38.7345 | 682000 | 2.5 | '486849370.000' | '12586.49' | '487531370.00' | '528.500'
10 | 'Sunset Beach' | 30.975 | 350000 | 2 | '388444000.000' | '12551.86' | '388794000.00' | '528.000'
11 | 'Clover-n’-Over' | 39 | 530000 | 2.5 | '486046050.000' | '12476.31' | '486576050.00' | '528.500'
12 | 'Epic Chattanooga Choo' | 33.589499 | 366345 | 2.08 | '403994434.676' | '12038.31' | '404360779.68' | '528.080'
13 | 'Milly' | 36.75 | 210000 | 2.25 | '436029825.000' | '11870.47' | '436239825.00' | '528.250'
14 | 'Epic The Thrill Rider' | 36.644999 | 235410 | 2.08 | '403302993.128' | '11012.10' | '403538403.13' | '528.080'
15 | 'Epic Entminer' | 36.739499 | 398055 | 2.08 | '404161888.844' | '11011.58' | '404559943.84' | '528.080'
16 | 'Almost Switch' | 35.489475 | 582023 | 2 | '389669081.440' | '10996.25' | '390251104.44' | '528.000'
17 | 'AncLA' | 36.329475 | 724000 | 2 | '390418720.000' | '10766.54' | '391142720.00' | '528.000'
18 | 'Epic Hasher’s Egg' | 37.789499 | 390915 | 2.08 | '404124183.932' | '10704.43' | '404515098.93' | '528.080'
19 | 'Epic Sunseeker' | 37.789499 | 353115 | 2.08 | '403924569.692' | '10698.15' | '404277684.69' | '528.080'
20 | 'Washingtonian' | 36.645 | 448000 | 2 | '388961440.000' | '10626.54' | '389409440.00' | '528.000'
21 | 'Rare Target Flooff' | 30.45 | 385875 | 1.66 | '322910788.025' | '10617.30' | '323296663.02' | '527.660'
22 | 'Uncommon Hokusai' | 38.85 | 249375 | 2.1 | '407242749.375' | '10488.86' | '407492124.38' | '528.100'
23 | 'Uncommon El Monstro' | 39.889499 | 288750 | 2.1 | '407450688.750' | '10221.72' | '407739438.75' | '528.100'


</body>
</html>

That's what I get when I type in my current base power of 193.298.000 GHs - and my bonus power of 526%

But with Golden Fleece (#3 in the table) I should get 8,930.000 GHs in absolute power - 3% for 193,298 PHs = 5,79894 PHs and 529 % for 500.000 GHs = 2,645 PHs + normal power of 500.000 GHs - it seems the last calculation doesn't get added to the "addpower"

**Comment by CableKungZ** [comment]
![image](https://github.com/CableKungZ/RollercoinBestPower/assets/64020377/2b9532f9-5a4c-4557-92f8-2cbab4f7969b)
fixed it rn
i guess it work rn , but if isn't work sent more to me
